name: Cache Workflow

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: prime-cache-48796f4
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-48796f4
          restore-keys: |
            cache-

      - name: Echo cache result
        run: |
          if [ "${{ steps.cache.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi
