name: Cache Workflow

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: prime-cache-48796f4
        id: prime-cache-48796f4
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-48796f4
          restore-keys: |
            cache-

      - name: Echo cache hit/miss
        run: echo "Cache hit: ${{ steps.prime-cache-48796f4.outputs.cache-hit }}"
